version: '3.4'

volumes:
  dbpgsql:

services:
#   db:
#     image: postgres
#     container_name: db
#     restart: always
#     ports:
#         - 5432:5432
#     # volumes:
#     #     - dbpgsql:/docker-entrypoint-initdb.d/
#     environment:
#         POSTGRES_USER: postgres
#         POSTGRES_PASSWORD: pass123
#         POSTGRES_DB: postgres
    pgsql:
        image: postgres:9.6
        container_name: db
        restart: unless-stopped
        expose:
            - 5433
        ports:
            - ${DB_PORT:-5433}:5432
        volumes:
            - dbpgsql:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass123
            POSTGRES_DB: postgres

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - ${ADMINER_PORT_DB:-8080}:8080
        environment:
            - ADMINER_DEFAULT_SERVER=pgsql
            - ADMINER_DESIGN=price
